# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoanCalc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoanCalc
  pod 'Parse'
  pod 'Charts'

  target 'LoanCalcTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LoanCalcUITests' do
    # Pods for testing
  end

end
